// <auto-generated />
namespace DevCode.webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class criabanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criabanco));
        
        string IMigrationMetadata.Id
        {
            get { return "202304212138560_cria-banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
