// <auto-generated />
namespace DevCode.webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addimagefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addimagefields));
        
        string IMigrationMetadata.Id
        {
            get { return "202304262008145_add-image-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
